### ISSUE TITLE
Unmonitor items

### ISSUE THREAD

**Issue by coussej** [node-opcua/opcua-commander#1]
I can't seem to unmonitor an item. When the item monitored is selected in the tree and i press **u**, nothing happens. I also can't change the selection to monitored items, only to Address Space (tree) and Attribute list.

**Comment by coussej** [comment]
I just saw in the code that this is a TODO :) that seems to explain why it's not working !

**Comment by erossignon** [comment]
Please feel free to contribute and provide some help if you can.

**Comment by coussej** [comment]
Created a pull request with this functionality!
