### ISSUE TITLE
Seeing a Back off error

### ISSUE THREAD

**Issue by alexdumitrescu** [node-opcua/opcua-commander#16]
Attached is an image of the error I am seeing when I run my OPC connection. 

I am connecting using Security= None. 
I made the necessary changes to two files (packages/node-opcua-client/src/opcua_client.js and packages/node-opcua-secure-channel/src/security_policy.js) based on this issue:
Updated:
https://github.com/node-opcua/node-opcua/pull/451/files#diff-071a8e480403d352c67d8d127f6c9e4e

 Once these changes were made, I built out my certificate and ran npm install.
Next I started the OPC Server and saw the following:

![opc cli issue](https://user-images.githubusercontent.com/23464261/46048025-59bed800-c0f5-11e8-8bc5-ed99a27f4722.PNG)

I am running Node V9.0.0, npm V5.5.1

Do you have any idea why the final step in the connection is not going through? This exact process was working for me a few months ago.

**Comment by alexdumitrescu** [comment]
I updated the link above to reflect the actual changes in the program. Any insights would be very helpful.

**Comment by erossignon** [comment]
backoff message indicates that the server is not reachable and a attempt to reconnect will happen soon.
