### ISSUE TITLE
Error: Cannot find module 'xml-writer'

### ISSUE THREAD

**Issue by lsdeef** [node-opcua/opcua-commander#23]
After installing opcua-commander got the following while trying to start it:

`[root@monitor bin]# opcua-commander
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'xml-writer'
Require stack:
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-xml2json/dist/source/fragmentCloner.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-xml2json/dist/source/index.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-schemas/dist/source/parse_binary_xsd.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-schemas/dist/source/index.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client-dynamic-extension-object/dist/client_dynamic_extension_object.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client-dynamic-extension-object/dist/index.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/private/client_session_impl.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/private/opcua_client_impl.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/opcua_client.js
- /usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/index.js
- /usr/lib/node_modules/opcua-commander/index.js
- /usr/lib/node_modules/opcua-commander/bin/opcua-commander
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-xml2json/dist/source/fragmentCloner.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-xml2json/dist/source/fragmentCloner.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-xml2json/dist/source/index.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-schemas/dist/source/parse_binary_xsd.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-schemas/dist/source/index.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client-dynamic-extension-object/dist/client_dynamic_extension_object.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client-dynamic-extension-object/dist/index.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/private/client_session_impl.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/private/opcua_client_impl.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/opcua_client.js',
    '/usr/lib/node_modules/opcua-commander/node_modules/node-opcua-client/dist/index.js',
    '/usr/lib/node_modules/opcua-commander/index.js',
    '/usr/lib/node_modules/opcua-commander/bin/opcua-commander'
  ]
}
`

I've installed the xml-writer

**Comment by aschaepper** [comment]
Same here, not a big deal thou.

**Comment by erossignon** [comment]
Should be fixed in version 0.8.0 that includes node-opcua@2.5.1
( issue was related to /node-opcua/node-opcua/issues/734 ) 

@aschaepper  @Lsdeef please confirm

**Comment by erossignon** [comment]
Now fixed in 0.8.2
