### ISSUE TITLE
Variable structure crashes commander

### ISSUE THREAD

**Issue by biancode** [node-opcua/opcua-commander#9]
Dear Etienne,

I tried to read an OPC UA Variable with structure and it crashes the commander every time.
I know it is not UAExpert, but there it works well. It would be great if the commander will support such Variable structures.

![image](https://user-images.githubusercontent.com/4369867/27258744-0f50a27c-5403-11e7-943f-633c403b0718.png)

![image](https://user-images.githubusercontent.com/4369867/27258747-2382150a-5403-11e7-9309-05506e870554.png)

![image](https://user-images.githubusercontent.com/4369867/27258751-409c4c1e-5403-11e7-8601-aa56c9e33ed4.png)

Thank you for your time!
Happy coding!
Klaus

**Comment by erossignon** [comment]
Hi Klaus, are you using latest opcua-commander version ? should be 0.1.12

**Comment by biancode** [comment]
Oh, no. new version 12 hours ago - I see - Yes it works very well. Thank you!

**Comment by biancode** [comment]
![image](https://user-images.githubusercontent.com/4369867/27259386-937e19d0-5412-11e7-90f8-1f0aaa36d38e.png)
